matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - phpenv global 7.1
        - cp .env.travis .env
        - mysql -e 'create database homestead_test;'
        - composer self-update
        - composer install --no-interaction
        - sudo apt-get install chromium-chromedriver
        - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        - php artisan key:generate
        - php artisan migrate --database=testing
        - php artisan passport:install
        - php artisan serve&
        - sleep 5
        - cd tests/python
      script:
        - python tests.py --url http://127.0.0.1:8000/ --genusers

    - language: php
      php:
        - 7.1
      script:
        - vendor/bin/phpunit


language: php
php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --database=testing
  - php artisan passport:install


